package main

import (
	"bytes"
	"embed"
	"fmt"
	"io"
	"io/fs"
)

// embeddedFS holds the build artifacts the launcher unpacks at run time:
//
//	embedded/backend.zip    — the per-platform Go backend binary, zipped
//	embedded/dashboard.zip  — the PyInstaller onedir freeze of the dashboard
//
// These are generated by the build scripts (packaging/scripts/build.sh and
// build-windows.ps1) *before* the launcher is compiled, so a real build bakes
// them in. They are git-ignored, not committed.
//
// We embed the whole directory rather than each zip by name. A file embed
// (//go:embed embedded/backend.zip) is a compile error when the target is
// missing, which would stop a fresh clone from even compiling. A directory
// embed compiles against whatever the dir contains — a committed .gitkeep on a
// fresh clone, the real zips after a build — so `go build`/`go vet` always
// work. The trade-off is that a missing artifact becomes a clear runtime error
// (see readEmbedded) instead of a compile error; every real build populates the
// dir first, so that path is unaffected.
//
//go:embed embedded
var embeddedFS embed.FS

// readEmbedded loads a named artifact from the embedded directory, returning a
// helpful error if it is absent (i.e. the binary was compiled without a build
// step having generated the zips).
func readEmbedded(name string) (io.ReaderAt, int64, error) {
	b, err := fs.ReadFile(embeddedFS, "embedded/"+name)
	if err != nil {
		return nil, 0, fmt.Errorf(
			"embedded %s is missing — this launcher was built without its "+
				"artifacts; build it via packaging/scripts/build.sh: %w", name, err)
	}
	return bytes.NewReader(b), int64(len(b)), nil
}

func backendZip() (io.ReaderAt, int64, error)   { return readEmbedded("backend.zip") }
func dashboardZip() (io.ReaderAt, int64, error) { return readEmbedded("dashboard.zip") }
